@echo off
echo Server wordt gestart...
SET "PATH=C:\Program Files\nodejs;%PATH%"
echo Even wachten... Prisma client wordt gegenereerd...
call npm run postinstall
echo Nu start de website...
npm run dev
pause
